#!/bin/sh

YELLOW='\033[1;33m'
GREEN='\033[1;32m'
project() 
{
    echo -e "${YELLOW}Updating NPM Deps"
    npm update
    echo -e "${GREEN}Update Complete"
}

templates() 
{
    echo -e "${YELLOW}Updating Template Deps"
    for directory in $(ls _templates)
    do
            echo -e "${YELLOW}Updating NPM Deps for [${directory}]"
            cd _templates/$directory && npm update
            echo -e "${GREEN}Update Complete for [${directory}]"
            cd ../../
    done
    echo "Hello World"
    echo -e "${GREEN}Update Complete"
}

"$@"